name: when_yes
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

# DEPENDECY IMPOR FONT DARI GOOGLE FONTS
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.18.1
  table_calendar: ^3.0.9

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1 # Buat impor ikon aplikasi
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # SECTION IMPOR ASSET BADGE DARI FOLDER 'ASSETS'
  assets:
    - assets/logo.png

# SECTION IMPOR FONT DARI FOLDER 'FONTS'
fonts:
  - family: DMSans
    fonts:
      - asset: fonts/DMSans-Regular.ttf
      - asset: fonts/DMSans-Medium.ttf
        weight: 500
      - asset: fonts/DMSans-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: fonts/DMSans-Italic.ttf
        style: italic
      - asset: fonts/DMSans-Bold.ttf
        weight: 700
      - asset: fonts/DMSans-BoldItalic.ttf
        weight: 700
        style: italic

# IMPOR IKON APLIKASI DARI ASSETS
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package